name: env_eesc 
channels:
  - defaults
dependencies:
  - python=3
  - jupyterlab=0.35.1
  - numpy
  - pandas
  - scikit-learn=0.20
  - wget
  - matplotlib
  - h5py
  - xarray
  - netcdf4
  - cartopy 

